name: "app_dev"

services:

  postgres:
    image: postgres:16-alpine
    container_name: app_postgres
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: superpassword
      POSTGRES_DB: appdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U superuser -d appdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - "app-postgres:/var/lib/postgresql/data"


volumes:
  app-postgres:
